bin = [
  { name = "todo", path = "src/main.rs" },
]

[package]
name = "todo"
edition = "2021"
# Don't publish the exercises on crates.io!
publish = false

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[lints.rust]
# You shouldn't write unsafe code in Rustlings!
unsafe_code = "forbid"
# You don't need unstable features in Rustlings and shouldn't rely on them while learning Rust.
unstable_features = "forbid"
# Dead code warnings can't be avoided in some exercises and might distract while learning.
dead_code = "allow"

[lints.clippy]
# You forgot a `todo!()`!
todo = "forbid"
allow-unwrap-in-tests = "allow"
unwrap_used = "forbid"
# This can only happen by mistake in Rustlings.
empty_loop = "forbid"
# No infinite loops are needed in Rustlings.
infinite_loop = "deny"
# You shouldn't leak memory while still learning Rust!
mem_forget = "deny"
# Currently, there are no disallowed methods. This line avoids problems when developing Rustlings.
disallowed_methods = "allow"

[package.metadata.scripts]
console = "MODE=console cargo run"
web = "MODE=web cargo run"

[dependencies]
comfy-table = "7.1.4"
serde = {  version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
chrono = "0.4.39"
axum = {  version = "0.8.1", features = ["macros"] }
tokio ={ version = "1.43", features = ["rt-multi-thread", "macros"] }
postgres = "0.19.2"
tokio-postgres = "0.7.13"
postgres-native-tls = "0.5.1"
native-tls = "0.2.14"

futures = "0.3.31"
tower-http = { version = "0.6.2", features = ["cors"]}
tower = "0.5.2"
tracing-subscriber = "0.3.19"
tracing = "0.1.41"
tracing-appender = "0.2.3"



